### ISSUE TITLE
Command request: shorten - shorten links from the comfort of Slack

### ISSUE THREAD

**Issue by craigcabrey** [rit-sse/slushy#5]
Pretty self-explanatory.

Officers:
- `/sse shorten [link]`
  - `Shortened to: [shortened link]`

Pinocchio requires a login, but we can add an exception for the slushy service and let slushy / the API do the auth.

**Comment by bbesmanoff** [comment]
I think the goal is to keep links coming from SSE legit.  Anyone can use bitly or the like, but officers make SSE links

**Comment by craigcabrey** [comment]
Makes sense, updated description.

**Comment by bbesmanoff** [comment]
Should this command also accept the short url (`/sse shorten link short_link`)?

Also, should this command perform expansion (`/sse shorten short_link` returns `link`)?
